### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by Crni39** [niikoolaa04/nikolaa.me-site#1]
I'm 17yo

> Lik zvuči kao 13yo

Ja nmg

**Comment by niikoolaa04** [comment]
![Screenshot_20210731_153113](https://user-images.githubusercontent.com/50048979/127741450-bd9feb3e-a33a-4ae4-87d0-e74f31677725.jpg)

**Comment by niikoolaa04** [comment]
Usput kadće naučimo gramatiku.

**Comment by Crni39** [comment]
Šta je nepravopisno u slici?

**Comment by Crni39** [comment]
I počeo sam da pričam, ali ne s budalama 🤗

**Comment by niikoolaa04** [comment]
> Šta je nepravopisno u slici?

"puta" a u ovoj mislim da reč "nepravopisno" ne postoji

**Comment by Crni39** [comment]
šta je krivo u "puta"? Googlaj ne zajebavaj me

**Comment by niikoolaa04** [comment]
> šta je krivo u "puta"? Googlaj ne zajebavaj me

Care kaže se "zadnji put" a ne "zadnji putA" usput umesto "zadnji" ide "poslednji"

**Comment by Crni39** [comment]
Ne odblokiram te nikada

**Comment by niikoolaa04** [comment]
> Ne odblokiram te nikada

Ajde brate dase pomirimo ozbiljan sam

**Comment by Crni39** [comment]
> > Ne odblokiram te nikada
> 
> Ajde brate dase pomirimo ozbiljan sam

Odjebi lol

**Comment by Crni39** [comment]
Ja sam prošao preko toga, ja mogu i bez vas živjeti, nema rasprave, doviđenja
